#!/bin/bash
# shellcheck disable=SC2086


log_enter pENV

source sENV.sh


export PROJ_LABEL=$SYS
export PROJ_NET=$SYS_NET

export PROJ_CONT=$PORT_CONT
export PROJ_CONT_DIR=$PORT_CONT_DIR
export PROJ_CONT_HOME_DIR=$PORT_CONT_HOME_DIR
export PROJ_HOST=$PORT_HOST
export PROJ_HOST_DIR=$PORT_HOST_DIR
export PROJ_IMG=$PORT_IMG
export PROJ_PASSWORD=$PORT_PASSWORD
export PROJ_PORT_EXT=$PORT_PORT_EXT
export PROJ_PORT_INT=$PORT_PORT_INT
export PROJ_USER=$PORT_USER
export PROJ_VOL=$PORT_VOL
export PROJ_VOL_DIR=$PORT_VOL_DIR

export PROJ_CONT_DATA_DIR=$PORT_CONT_DATA_DIR
export PROJ_HOST_DATA_DIR=$PORT_HOST_DATA_DIR

log_exit pENV