@echo off


CALL LOG_ENTER pENV

CALL sENV

SET "PROJ_LABEL=%SYS%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%PG_CONT%"
SET "PROJ_CONT_DATA_DIR=%PG_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%PG_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%PG_CONT_HOME_DIR%"
SET "PROJ_HOST=%PG_HOST%"
SET "PROJ_HOST_DIR=%PG_HOST_DIR%"
SET "PROJ_IMG=%PG_IMG%"
SET "PROJ_PASSWORD=%PG_PASSWORD%"
SET "PROJ_PORT_EXT=%PG_PORT_EXT%"
SET "PROJ_PORT_INT=%PG_PORT_INT%"
SET "PROJ_USER=%PG_USER%"
SET "PROJ_VOL=%PG_VOL%"
SET "PROJ_VOL_DIR=%PG_VOL_DIR%"

CALL LOG_EXIT pENV
